# Titanic

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [4]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [5]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [6]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

female   male
0   False   True
1    True  False
2    True  False

In [7]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

In [8]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [9]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(10)

Pclass        Age     Fare  female
0       3  22.000000   7.2500   False
1       1  38.000000  71.2833    True
2       3  26.000000   7.9250    True
3       1  35.000000  53.1000    True
4       3  35.000000   8.0500   False
5       3  29.699118   8.4583   False
6       1  54.000000  51.8625   False
7       3   2.000000  21.0750   False
8       3  27.000000  11.1333    True
9       2  14.000000  30.0708    True

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [11]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [12]:
model.fit(X_train,y_train)

GaussianNB()

In [13]:
model.score(X_test,y_test)

0.7835820895522388

In [15]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [16]:
model.fit(X_train,y_train)

MultinomialNB()

In [17]:
model.score(X_test,y_test)

0.6902985074626866

In [20]:
model.predict(X_test)

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int64)

In [19]:
model.predict_proba(X_test)

array([[1.52172372e-03, 9.98478276e-01],
       [9.65883687e-01, 3.41163132e-02],
       [3.09309500e-05, 9.99969069e-01],
       [9.99988150e-01, 1.18496582e-05],
       [9.99950525e-01, 4.94748908e-05],
       [9.99546671e-01, 4.53329029e-04],
       [9.99999016e-01, 9.83558519e-07],
       [9.99996496e-01, 3.50371953e-06],
       [9.98301612e-01, 1.69838842e-03],
       [9.99996011e-01, 3.98876108e-06],
       [9.99996515e-01, 3.48484237e-06],
       [7.17522419e-07, 9.99999282e-01],
       [9.99596371e-01, 4.03629465e-04],
       [9.99990395e-01, 9.60481903e-06],
       [9.99994942e-01, 5.05830721e-06],
       [9.98743815e-01, 1.25618511e-03],
       [9.99997202e-01, 2.79754700e-06],
       [9.99807113e-01, 1.92886566e-04],
       [9.99989241e-01, 1.07586796e-05],
       [9.99998157e-01, 1.84261777e-06],
       [9.99988559e-01, 1.14406118e-05],
       [9.99812925e-01, 1.87074936e-04],
       [9.65244517e-15, 1.00000000e+00],
       [7.34765929e-02, 9.26523407e-01],
       [9.999924

In [ ]:
#Calculate the score using cross validation

In [22]:
from sklearn.model_selection import cross_val_score
cross=cross_val_score(GaussianNB(),X_train, y_train, cv=5)

In [23]:
cross.mean()

0.7542451612903227

In [24]:
from sklearn.model_selection import cross_val_score
cross=cross_val_score(MultinomialNB(),X_train, y_train, cv=5)

In [25]:
cross.mean()

0.6966967741935484

# ADS prediction


In [26]:
dataset = pd.read_csv('user_data.csv') 
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [27]:
x = dataset.iloc[:, [2, 3]].values  
y = dataset.iloc[:, 4].values  

In [28]:
# Splitting the dataset into the Training set and Test set  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)  

In [29]:
# Feature Scaling  
from sklearn.preprocessing import StandardScaler  
sc = StandardScaler()  
x_train = sc.fit_transform(x_train)  
x_test = sc.transform(x_test)  

In [30]:
# Fitting Naive Bayes to the Training set  
from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(x_train, y_train) 

GaussianNB()

In [31]:
y_pred = classifier.predict(x_test) 

In [32]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [33]:
y_pred1 = classifier.predict([[ 0.38358493,  0.99784738]])   # array[1] means Buy the car 
y_pred1

array([1], dtype=int64)

In [34]:
# Making the Confusion Matrix  
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred)  

In [35]:
cm

array([[65,  3],
       [ 7, 25]], dtype=int64)

In [36]:
65+25   #90 percentage ic correct model

90

In [37]:
7+3   # 10 percentage is incorrect model/

10

In [38]:
classifier.score(x_test,y_test)

0.9

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
accu=accuracy_score(y_test,y_pred)
accu

0.9